### ISSUE TITLE
Front End HTML Templates

### ISSUE THREAD

**Issue by davidsaulrodriguez** [davidsaulrodriguez/project-purple-planet#3]
The front end of this website needs to be designed and put together.

At minimum this front end should consist of a standard index or landing page, the signup and login forms, as well as the member's index page.

needed for first snapshot on `main` branch

- [x] Index Page
- [x] Login Page (resolved with pr #10)
- [x] Signup Page (resolved with pr #10)
- [x] Member Dashboard (index of logged in user)
- [x] separate Tasks pages for individual boards

The front end mvp templates should also be using handlebars to dynamically display data.

**Comment by JCyberAI** [comment]
I have each task card handlebar file (to-do, in-progress, review, and completed ready to be commited.

**Comment by davidsaulrodriguez** [comment]
This issue is partially solved with Pull Request #10

**Comment by davidsaulrodriguez** [comment]
PR #26 partially solves this issue as well.
